.circleci/config.yml
.gitignore
eject.py
python/plotly-express.md
resync.py

upgrade px to idiom

---

python/getting-started.md
requirements.txt

Update getting_started and requirements.txt to final versions

---

python/facet-plots.md

cc @nicolaskruchten @emmanuelle

remove whitespace in link

---

python/parallel-categories-diagram.md

Parallel category V4

---

.circleci/config.yml
python/getting-started.md
python/plotly-express.md
requirements.txt

Update release versions to 4.1.0 final. Update requirements.txt to 4.1.0rc2 to test on CI.

Plotly version 4.1.0 docs update

---

python/bar-charts.md

Doc upgrade checklist:
closes https://github.com/plotly/documentation/issues/1450

categoryorder in python bar chart

---

python/ternary-contour.md
requirements.txt

New notebook for recent figure factory.

ternary contour notebook

---

python/ohlc-charts.md

As a part of https://github.com/plotly/documentation/pull/1338, this will line up the thumbnails in the main python index page after that is merged.
Doc upgrade checklist is not applicable.

remove from python index page after adding index

---

python/sunburst-charts.md

upgrading sunburst

---

python/sunburst-charts.md

Update description for sunburst basic example

---

apidoc/conf.py

This is not the default in sphinx, since in rst code is with double backticks (backquotes).

interpret backticks as code

---

python/images.md

Doc upgrade checklist:
---
https://plot.ly/python/images/#zoom-on-static-images
This PR proposes to disable `autosize` on double click and use only `reset` because `autosize` adds margins around the image.

Disable autosize on double click

---

python/images.md
requirements.txt

This PR updates `scipy` to the current latest version `1.3.1` ([release history](https://pypi.org/project/scipy/#history)) to resolve #148.

Update scipy to the current latest version to suppress FutureWarning

---

binder/requirements.txt

Following this PR #153, `scipy` and `statsmodels` for Binder should be updated.
---
Doc upgrade checklist:

Update scipy and statsmodels for Binder

---

python/network-graphs.md

Fixing typo in Create Edges example code.  
(G.node -> G.nodes)
Doc upgrade checklist:

[Fix] Fix typo (G.node -> G.nodes)

---

python/templates.md

Document `simple_white` template as per https://github.com/plotly/plotly.py/pull/1874#issuecomment-549939876

Document simple_white template

---

python/shapes.md
python/text-and-annotations.md

I did not replace all `update_layout(annotations=[...])` by `add_annotation` because I feel like sometimes the `update_layout` syntax is nice for adding a bunch of objects (and it always works when you don't know that the `add_*` methods exist) but I'm open to changing all occurrences.

document new methods add_shape add_annotation

---

.circleci/config.yml

The purpose of this PR is to update the CircleCI `config.yml` so that it fetches the `check-or-enforce-order` script from the `documentation` repo and runs it at build time.

Update Circle CI to check order of posts

---

python/sankey-diagram.md

resolves https://github.com/plotly/documentation/issues/1589

sankey nodes position

---

python/axes.md
python/creating-and-updating-figures.md
python/histograms.md
python/parallel-categories-diagram.md
python/parallel-coordinates-plot.md
python/pie-charts.md

closes https://github.com/plotly/documentation/issues/1496

cross-linking between tutorials

---

python/colorscales.md

I was searching how to customize the colorscale ticks and found this example. Having a more descriptive title will make this example easier to find.
cc @Mahdis-z @nicolaskruchten @emmanuelle

Make custom colorscale title example more descriptive
